### ISSUE TITLE
建议投降🌝

### ISSUE THREAD

**Issue by xianquu** [luyii-code-1/Captcha-with-CPC#1]
资本主义青年团军方已经派兵轰炸你的网页了🌝
如果你不投降，luyii.cn网页将永久报废🌝

**TCO剿匪司令部下令调集大量联合电子作战资源清剿“卢意叛军势力”**

打击星火的行动也在规划了🌝

资本主义青年团(TCO)总官
**皇帝睿**
![团旗](https://github.com/luyii-code-1/Captcha-with-CPC/assets/160004827/b71c434f-c6cb-47b0-9f7a-4fc0d46a640b)

**Comment by luyii-code-1** [comment]
随便你，反正你轰炸不掉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月28日(周五) 中午1:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [luyii-code-1/Captcha-with-CPC] 建议投降🌝 (Issue #1)




 
资本主义青年团军方已经派兵轰炸你的网页了🌝
 如果你不投降，luyii.cn网页将永久报废🌝
 
TCO剿匪司令部下令调集大量联合电子作战资源清剿“卢意叛军势力”
 
打击星火的行动也在规划了🌝
 
资本主义青年团(TCO)总官
 皇帝睿
 IMG_3154.jpeg (view on web)

**Comment by luyii-code-1** [comment]
反正越大的攻击往往只需要最简单的方法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月28日(周五) 中午1:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [luyii-code-1/Captcha-with-CPC] 建议投降🌝 (Issue #1)




 
资本主义青年团军方已经派兵轰炸你的网页了🌝
 如果你不投降，luyii.cn网页将永久报废🌝
 
TCO剿匪司令部下令调集大量联合电子作战资源清剿“卢意叛军势力”
 
打击星火的行动也在规划了🌝
 
资本主义青年团(TCO)总官
 皇帝睿
 IMG_3154.jpeg (view on web)
