### ISSUE TITLE
null

### ISSUE THREAD

**Issue by tcomil** [luyii-code-1/Captcha-with-CPC#2]
null

**Comment by luyii-code-1** [comment]
随便你，国家支持实名上网，你这样就是在支持我



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月7日(周六) 下午5:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [luyii-code-1/Captcha-with-CPC] 你如果再不投降 我就发到X上 (Issue #2)




 
你以为我不敢发吗?欧阳云睿开盒信息已经发了
 
https://x.com/bukaixyz/status/1832295895116980305?s=61
 
之前扰乱军方情报局 阻碍军方剿灭星火 背叛我团和SFA的卢意叛军卑鄙小人被安全局开盒了🌝(开盒信息有删减)
 
姓名:  卢意
 身份证号:  33028120090831001X
 身份证归属地： 浙江省-宁波市-余姚市
 
🎉 数据来源: 「 学籍 」🎉
 ✨姓名：卢意
 ✨身份证：33028120090831001X (浙江省宁波市余姚市 男 15岁)
 ✨地区：浙江省余姚市
 ✨家长姓名：卢伯军
 ✨手机：13958389559 (浙江 宁波 移动)
 ✨地址：君悦国际1-2201
 ✨市县：浙江省余姚市
 ✨班级：小学三年级(01)班
 ✨学校：余姚市东城小学
 
🎉 数据来源: 「 志愿汇中国 」🎉
 ✨姓名：卢意
 ✨身份证：33028120090831001X (浙江省宁波市余姚市 男 15岁)
 ✨手机：13819433049 (浙江 宁波 移动)
 ✨省区：浙江省
 ✨市区：宁波市
 ✨县区：余姚市
 ✨政治面貌：群众
 ✨组织：宁波市志愿者协会（新） 区县(市)志愿者协会 余姚市志愿者协会; 宁波志愿者 县(市)区志愿者协会 余姚市志愿者协会; 浙江省 宁波市 宁波志愿者
 
🎉 数据来源: 「 银行数据库 」🎉
 ✨姓名：卢意
 ✨身份证：33028120090831001X (浙江省宁波市余姚市 男 15岁)
 ✨手机：13819433049 (浙江 宁波 移动)
 ✨省：浙江省
 ✨市：宁波市
 ✨用户：5555044843753575145
 ✨银行：工商银行 牡丹灵通卡
 
🎉 数据来源: 「 学籍 」🎉
 ✨姓名：卢愿(是卢意叛军的双胞胎 情报局之前也猜测🌝)
 ✨身份证：330281200908310036 (浙江省宁波市余姚市 男 15岁)
 ✨地区：浙江省余姚市
 ✨家长姓名：卢伯军
 ✨手机：13958389559 (浙江 宁波 移动)
 ✨地址：君悦国际1-2201
 ✨市县：浙江省余姚市
 ✨班级：小学三年级(01)班
 ✨学校：余姚市东城小学
 
🎉 数据来源: 「 银行数据库 」🎉
 ✨姓名：卢愿
 ✨身份证：330281200908310036 (浙江省宁波市余姚市 男 15岁)
 ✨手机：13819433049 (浙江 宁波 移动)
 ✨省：浙江省
 ✨市：宁波市
 ✨用户：55559510959055018
 ✨银行：中信银行 中信贵宾卡(银联卡)

**Comment by tcomil** [comment]
你以为我不敢发?🌝
https://x.com/bukaixyz/status/1832465355652174083?s=61
